services:
  localstack:
    image: localstack/localstack:stable
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs,s3 # Add or remove services as needed
      - DEBUG=1
      - EXTRA_CORS_ALLOWED_ORIGINS="*"
      - LS_LOG=trace
    volumes:
      - /home/bott/datos/edit/programacion/ASO/spacecat-audit-worker/zarf/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
